title: APIOps&reg; Cycles
description: APIOps&reg; Cycles is a method for designing API management compatible APIs with clear business orientation and best architecture patterns.
show_downloads: false
google_analytics: UA-104902537-1
theme: jekyll-theme-cayman
permalink: slug
